# Generated by Django 3.2 on 2021-04-17 03:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('orderedStatus', models.BooleanField(default=False)),
                ('orderDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('bsb', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('bankAccount', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('customerAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('COL', 'Coles'), ('WOO', 'Woolworths'), ('IGA', 'IGA'), ('ALD', 'ALDI')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerychain')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerychain')),
            ],
        ),
        migrations.CreateModel(
            name='PostCodeCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.item')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationDetails', models.CharField(blank=True, default='debug test', max_length=300, null=True)),
                ('pickupWhen', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.customerprofile')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerystore')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoiceGenerated', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.customerprofile')),
                ('prices', models.ManyToManyField(to='growocery.Price')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerystore')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.customerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerychain')),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.postcodecommunity'),
        ),
        migrations.CreateModel(
            name='CommunityGroceryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextDeadline', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.cart')),
                ('pcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.postcodecommunity')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='growocery.pickup')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerystore')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='volunteers', to='growocery.Pickup')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='combinedOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinedOrder', to='growocery.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='groupOrders',
            field=models.ManyToManyField(blank=True, null=True, related_name='groupOrders', to='growocery.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.grocerystore'),
        ),
    ]
