# Generated by Django 3.0.6 on 2021-04-16 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('bsb', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('bankAccount', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('customerAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
