# Generated by Django 3.1 on 2021-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='locationDetails',
            field=models.CharField(blank=True, default='Undecided', max_length=300, null=True),
        ),
    ]
