# Generated by Django 3.2 on 2021-04-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.communitygrocerygroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.customerprofile')),
            ],
        ),
    ]
