# Generated by Django 3.0.6 on 2021-04-16 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orderedStatus', models.BooleanField(default=False)),
                ('orderDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroceryChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('COL', 'Coles'), ('WOO', 'Woolworths'), ('IGA', 'IGA'), ('ALD', 'ALDI')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('img', models.CharField(max_length=50)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryChain')),
            ],
        ),
        migrations.CreateModel(
            name='PostCodeCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationDetails', models.CharField(max_length=300)),
                ('pickupWhen', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.CustomerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoiceGenerated', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.CustomerProfile')),
                ('items', models.ManyToManyField(to='growocery.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.CustomerProfile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.Order')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryChain')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryChain')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityGroceryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextDeadline', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.Cart')),
                ('pcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='growocery.PostCodeCommunity')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='growocery.Pickup')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryStore')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='volunteers', to='growocery.Pickup')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='combinedOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinedOrder', to='growocery.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='groupOrders',
            field=models.ManyToManyField(related_name='groupOrders', to='growocery.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryStore'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.PostCodeCommunity'),
        ),
    ]
