# Generated by Django 3.0.6 on 2021-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprice',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
