# Generated by Django 3.2 on 2021-04-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
