# Generated by Django 3.0.6 on 2021-04-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0002_auto_20210416_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygrocerygroup',
            name='pcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.PostCodeCommunity'),
        ),
    ]
