# Generated by Django 3.1 on 2021-04-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0002_auto_20210417_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='buyer',
            field=models.ForeignKey(blank=True, default='Undecided', null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.customerprofile'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='locationDetails',
            field=models.CharField(blank=True, default='debug test', max_length=300, null=True),
        ),
    ]
