# Generated by Django 3.0.6 on 2021-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0003_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
