# Generated by Django 3.0.6 on 2021-04-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0003_auto_20210417_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='combinedOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combinedOrder', to='growocery.Order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='groupOrders',
            field=models.ManyToManyField(blank=True, null=True, related_name='groupOrders', to='growocery.Order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orderDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.GroceryStore'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
