# Generated by Django 3.2 on 2021-04-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0003_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='locationDetails',
            field=models.CharField(blank=True, default='pending', max_length=300, null=True),
        ),
    ]
