# Generated by Django 3.0.6 on 2021-04-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0004_auto_20210417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.CustomerProfile'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='locationDetails',
            field=models.CharField(blank=True, default='debug test', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickupWhen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
