# Generated by Django 3.0.6 on 2021-04-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0005_auto_20210417_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='growocery.Item'),
        ),
    ]
