# Generated by Django 3.0.6 on 2021-04-17 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growocery', '0006_item_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='link',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growocery.Item')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prices',
            field=models.ManyToManyField(to='growocery.Price'),
        ),
    ]
